--------------------------------------------------------
--  File created - Friday-November-08-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MASTERPLAN
--------------------------------------------------------

  CREATE TABLE "TEAM3"."MASTERPLAN" 
   (	"MASTERPLANNUMBER" NUMBER(2 BYTE), 
	"MASTERPLANDESC" VARCHAR2(100 BYTE), 
	"STARTDATE" VARCHAR2(20 BYTE), 
	"EXPECTEDENDDATE" VARCHAR2(20 BYTE), 
	"PRIORITY" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"PERCENTAGECOMPLETE" NUMBER(3 BYTE)
   ) 
   
   
Insert into TEAM3.MASTERPLAN (MASTERPLANNUMBER,MASTERPLANDESC,STARTDATE,EXPECTEDENDDATE,PRIORITY,STATUS,PERCENTAGECOMPLETE) values (5,'Delivery','2019-11-05','2019-11-22','high','active',23);
Insert into TEAM3.MASTERPLAN (MASTERPLANNUMBER,MASTERPLANDESC,STARTDATE,EXPECTEDENDDATE,PRIORITY,STATUS,PERCENTAGECOMPLETE) values (3,'Phillips Bulb','2019-10-30','2019-10-31','low','proposed',12);
Insert into TEAM3.MASTERPLAN (MASTERPLANNUMBER,MASTERPLANDESC,STARTDATE,EXPECTEDENDDATE,PRIORITY,STATUS,PERCENTAGECOMPLETE) values (12,'R&D on 6G','2019-10-01','2019-10-02','high','active',100);
Insert into TEAM3.MASTERPLAN (MASTERPLANNUMBER,MASTERPLANDESC,STARTDATE,EXPECTEDENDDATE,PRIORITY,STATUS,PERCENTAGECOMPLETE) values (2,'Microsoft project','2019-10-24','2019-10-31','high','active',12);
Insert into TEAM3.MASTERPLAN (MASTERPLANNUMBER,MASTERPLANDESC,STARTDATE,EXPECTEDENDDATE,PRIORITY,STATUS,PERCENTAGECOMPLETE) values (4,'HRIS system','2019-11-07','2022-07-21','normal','proposed',0);
Insert into TEAM3.MASTERPLAN (MASTERPLANNUMBER,MASTERPLANDESC,STARTDATE,EXPECTEDENDDATE,PRIORITY,STATUS,PERCENTAGECOMPLETE) values (1,'philips projects','2019-08-01','2019-09-01','high','proposed',21);

  
  
--------------------------------------------------------
--  Constraints for Table MASTERPLAN
--------------------------------------------------------

  ALTER TABLE "TEAM3"."MASTERPLAN" MODIFY ("MASTERPLANNUMBER" NOT NULL);
 
  ALTER TABLE "TEAM3"."MASTERPLAN" MODIFY ("MASTERPLANDESC" NOT NULL);
 
  ALTER TABLE "TEAM3"."MASTERPLAN" MODIFY ("PRIORITY" NOT NULL);
 
  ALTER TABLE "TEAM3"."MASTERPLAN" ADD PRIMARY KEY ("MASTERPLANNUMBER")
 
  ALTER TABLE "TEAM3"."MASTERPLAN" MODIFY ("STARTDATE" NOT NULL);
 
  ALTER TABLE "TEAM3"."MASTERPLAN" MODIFY ("EXPECTEDENDDATE" NOT NULL);
