--------------------------------------------------------
--  File created - Friday-November-08-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TASK
--------------------------------------------------------

  CREATE TABLE "TEAM3"."TASK" 
   (	"DEPTNUMBER" NUMBER(2 BYTE), 
	"PROJECTNUMBER" NUMBER(2 BYTE), 
	"TASKNUMBER" NUMBER(2 BYTE), 
	"TASKNAME" VARCHAR2(50 BYTE), 
	"STARTDATE" VARCHAR2(20 BYTE), 
	"DUEDATE" VARCHAR2(20 BYTE), 
	"PRIORITY" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"PERCENTAGECOMPLETE" NUMBER(3 BYTE), 
	"CONSTRAINTTYPE" VARCHAR2(30 BYTE), 
	"CONSTRAINTDATE" VARCHAR2(20 BYTE), 
	"SUMMARY" VARCHAR2(100 BYTE), 
	"DATECREATED" VARCHAR2(20 BYTE), 
	"LASTUPDATED" VARCHAR2(20 BYTE)
   ) 
Insert into TEAM3.TASK (DEPTNUMBER,PROJECTNUMBER,TASKNUMBER,TASKNAME,STARTDATE,DUEDATE,PRIORITY,STATUS,PERCENTAGECOMPLETE,CONSTRAINTTYPE,CONSTRAINTDATE,SUMMARY,DATECREATED,LASTUPDATED) values (1,1,13,'Bussiness Analytics Software testing','2019-11-07','2019-11-21','high','onHold',26,'Finish no earlier than','2019-11-06','It is on hold till 13th november.','2019-11-05','2019-11-05');
Insert into TEAM3.TASK (DEPTNUMBER,PROJECTNUMBER,TASKNUMBER,TASKNAME,STARTDATE,DUEDATE,PRIORITY,STATUS,PERCENTAGECOMPLETE,CONSTRAINTTYPE,CONSTRAINTDATE,SUMMARY,DATECREATED,LASTUPDATED) values (1,2,12,'DAAI','2019-11-05','2019-11-28','low','active',12,'Finish no earlier than','2019-11-18','Going good.','2019-11-05','2019-11-05');
Insert into TEAM3.TASK (DEPTNUMBER,PROJECTNUMBER,TASKNUMBER,TASKNAME,STARTDATE,DUEDATE,PRIORITY,STATUS,PERCENTAGECOMPLETE,CONSTRAINTTYPE,CONSTRAINTDATE,SUMMARY,DATECREATED,LASTUPDATED) values (3,3,78,'Daai','2019-11-14','2019-11-14','high','onHold',54,'Finish no earlier than','2019-11-28','ged','2019-11-13','2019-11-21');
Insert into TEAM3.TASK (DEPTNUMBER,PROJECTNUMBER,TASKNUMBER,TASKNAME,STARTDATE,DUEDATE,PRIORITY,STATUS,PERCENTAGECOMPLETE,CONSTRAINTTYPE,CONSTRAINTDATE,SUMMARY,DATECREATED,LASTUPDATED) values (1,2,1,'asd','2019-11-07','2019-11-12','high','active',12,'finish no later than','2019-11-14','asda','2019-11-12','2019-11-13');

  
--------------------------------------------------------
--  Constraints for Table TASK
--------------------------------------------------------

  ALTER TABLE "TEAM3"."TASK" MODIFY ("DEPTNUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "TEAM3"."TASK" MODIFY ("PROJECTNUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "TEAM3"."TASK" MODIFY ("TASKNUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "TEAM3"."TASK" MODIFY ("TASKNAME" NOT NULL ENABLE);
 
  ALTER TABLE "TEAM3"."TASK" MODIFY ("STARTDATE" NOT NULL ENABLE);
 
  ALTER TABLE "TEAM3"."TASK" MODIFY ("DUEDATE" NOT NULL ENABLE);
 
  ALTER TABLE "TEAM3"."TASK" MODIFY ("PRIORITY" NOT NULL ENABLE);
 
  ALTER TABLE "TEAM3"."TASK" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "TEAM3"."TASK" MODIFY ("PERCENTAGECOMPLETE" NOT NULL ENABLE);
 
  ALTER TABLE "TEAM3"."TASK" MODIFY ("DATECREATED" NOT NULL ENABLE);
 
  ALTER TABLE "TEAM3"."TASK" MODIFY ("LASTUPDATED" NOT NULL ENABLE);
 
  ALTER TABLE "TEAM3"."TASK" ADD CONSTRAINT "SYS_C0015274" PRIMARY KEY ("TASKNUMBER")
  
--------------------------------------------------------
--  Ref Constraints for Table TASK
--------------------------------------------------------

  ALTER TABLE "TEAM3"."TASK" ADD CONSTRAINT "TASK_FK1" FOREIGN KEY ("DEPTNUMBER")
	  REFERENCES "TEAM3"."DEPARTMENT" ("DEPTNUMBER") ENABLE;
 
  ALTER TABLE "TEAM3"."TASK" ADD CONSTRAINT "TASK_FK2" FOREIGN KEY ("PROJECTNUMBER")
	  REFERENCES "TEAM3"."PROJECT" ("PROJECTNUMBER") ENABLE;
