--------------------------------------------------------
--  File created - Friday-November-08-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROJECT
--------------------------------------------------------

  CREATE TABLE "TEAM3"."PROJECT" 
   (	"DEPTNUMBER" NUMBER(2 BYTE), 
	"PROJECTNUMBER" NUMBER(2 BYTE), 
	"PROJECTLEADER" VARCHAR2(20 BYTE), 
	"STARTDATE" VARCHAR2(20 BYTE), 
	"DUEDATE" VARCHAR2(20 BYTE), 
	"EXPECTEDTIME" NUMBER(5 BYTE), 
	"PRIORITY" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"PERCENTAGECOMPLETE" NUMBER(3 BYTE), 
	"PROJECTNAME" VARCHAR2(20 BYTE), 
	"PROJECTDESC" VARCHAR2(100 BYTE), 
	"MASTERPLANNUMBER" NUMBER(2 BYTE)
   )
   
   
Insert into TEAM3.PROJECT (DEPTNUMBER,PROJECTNUMBER,PROJECTLEADER,STARTDATE,DUEDATE,EXPECTEDTIME,PRIORITY,STATUS,PERCENTAGECOMPLETE,PROJECTNAME,PROJECTDESC,MASTERPLANNUMBER) values (8,1,'Shashi','2019-10-23','2019-09-24',100,'normal','hold',30,'Cisco Support','Providing 24x7 Support & Maintanance',3);
Insert into TEAM3.PROJECT (DEPTNUMBER,PROJECTNUMBER,PROJECTLEADER,STARTDATE,DUEDATE,EXPECTEDTIME,PRIORITY,STATUS,PERCENTAGECOMPLETE,PROJECTNAME,PROJECTDESC,MASTERPLANNUMBER) values (1,2,'Varsha','2019-11-04','2020-01-02',54,'high','proposed',1,'infosys support','support for Infy whistle blower',1);
Insert into TEAM3.PROJECT (DEPTNUMBER,PROJECTNUMBER,PROJECTLEADER,STARTDATE,DUEDATE,EXPECTEDTIME,PRIORITY,STATUS,PERCENTAGECOMPLETE,PROJECTNAME,PROJECTDESC,MASTERPLANNUMBER) values (6,3,'Shekhar Suman','2019-11-01','2020-05-09',42,'normal','active',5,'Legato Support','Backend and database support',3);
Insert into TEAM3.PROJECT (DEPTNUMBER,PROJECTNUMBER,PROJECTLEADER,STARTDATE,DUEDATE,EXPECTEDTIME,PRIORITY,STATUS,PERCENTAGECOMPLETE,PROJECTNAME,PROJECTDESC,MASTERPLANNUMBER) values (1,6,'Ankit','2020-01-22','2020-06-25',213,'normal','proposed',1,'Dassult Testing','Testing of 6G with dassault',12);
Insert into TEAM3.PROJECT (DEPTNUMBER,PROJECTNUMBER,PROJECTLEADER,STARTDATE,DUEDATE,EXPECTEDTIME,PRIORITY,STATUS,PERCENTAGECOMPLETE,PROJECTNAME,PROJECTDESC,MASTERPLANNUMBER) values (1,5,'Varsha','2019-10-24','2019-10-31',967,'high','active',98,'Microsoft Project','Windows 10.0',2);
Insert into TEAM3.PROJECT (DEPTNUMBER,PROJECTNUMBER,PROJECTLEADER,STARTDATE,DUEDATE,EXPECTEDTIME,PRIORITY,STATUS,PERCENTAGECOMPLETE,PROJECTNAME,PROJECTDESC,MASTERPLANNUMBER) values (20,4,'G Naik','2019-11-05','2019-11-30',123,'normal','active',12,'Dynamics','Manufacture Handling',4);

 
 
--------------------------------------------------------
--  Constraints for Table PROJECT
--------------------------------------------------------

  ALTER TABLE "TEAM3"."PROJECT" ADD CONSTRAINT "PROJECT_PK" PRIMARY KEY ("PROJECTNUMBER")
 
  ALTER TABLE "TEAM3"."PROJECT" MODIFY ("DEPTNUMBER" NOT NULL);
 
  ALTER TABLE "TEAM3"."PROJECT" MODIFY ("PROJECTLEADER" NOT NULL);
 
  ALTER TABLE "TEAM3"."PROJECT" MODIFY ("STARTDATE" NOT NULL);
 
  ALTER TABLE "TEAM3"."PROJECT" MODIFY ("DUEDATE" NOT NULL);
 
  ALTER TABLE "TEAM3"."PROJECT" MODIFY ("EXPECTEDTIME" NOT NULL);
 
  ALTER TABLE "TEAM3"."PROJECT" MODIFY ("PRIORITY" NOT NULL);
 
  ALTER TABLE "TEAM3"."PROJECT" MODIFY ("STATUS" NOT NULL);
 
  ALTER TABLE "TEAM3"."PROJECT" MODIFY ("PERCENTAGECOMPLETE" NOT NULL);
 
  ALTER TABLE "TEAM3"."PROJECT" MODIFY ("PROJECTNAME" NOT NULL);
 
  ALTER TABLE "TEAM3"."PROJECT" MODIFY ("MASTERPLANNUMBER" NOT NULL);
 
  ALTER TABLE "TEAM3"."PROJECT" MODIFY ("PROJECTNUMBER" NOT NULL);
--------------------------------------------------------
--  Ref Constraints for Table PROJECT
--------------------------------------------------------

  ALTER TABLE "TEAM3"."PROJECT" ADD CONSTRAINT "PROJECT_FK1" FOREIGN KEY ("DEPTNUMBER")
	  REFERENCES "TEAM3"."DEPARTMENT" ("DEPTNUMBER") ;
 
  ALTER TABLE "TEAM3"."PROJECT" ADD CONSTRAINT "PROJECT_FK2" FOREIGN KEY ("MASTERPLANNUMBER")
	  REFERENCES "TEAM3"."MASTERPLAN" ("MASTERPLANNUMBER") ;
